= Powerwall plugin for Teslasolarcharger

== Configuring the Docker image

Add the following lines to the `docker-compose.yml` file of Teslasolarcharger:

[source, yaml]
----
pwplugin:
    image: jbuchner/pwplugin:latest
    restart: always
    environment:
      - POWERWALL=<Address or IP>
      - USER_EMAIL=<Email>
      - USER_PASSWORD=<Password>
      - TZ=<TZ>
    ports:
      - 8081:8081
    container_name: teslasolarcharger_pwplugin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
----

Replace the variables `<Address or IP>`, `<Email>`, `<Password>` and `<TZ>` with the appropriate values for your Powerwall.

As value for TZ use the appropriate TZ identifier from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. For example, use the value `Europe/Berlin` for Germany.

Use

[source, sh]
----
docker compose up -d
----

to start the containers.

== Configure Teslasolarcharger

Open the base configuration of your Teslasolarcharger and configure the following endpoints.

=== Grid power

[cols="1,3"]
|===

| Source
| `REST`

| Grid Power Url
| `http://pwplugin:8081/aggregates`

| Result type
| `JSON`

| Grid Power Json Pattern
| `$.site`

| Grid Power Correction Factor
| `-1`

|===

=== Home Battery

[cols="1,3"]
|===

| Source
| `REST`

|===

==== Home Battery Soc

[cols="1,3"]
|===

| Home Battery Soc Url 
| `http://pwplugin:8081/soc`

| Result Type
| `JSON`

| Home Battery Soc Json Pattern
| `$.adjusted_soc`

| Home Battery Soc Correction Factor
| `1`

| Home Battery Minimum Soc 
|

|===

==== Home Battery Power

[cols="1,3"]
|===

| Home Battery Power Url 
| `http://pwplugin:8081/aggregates`

| Result Type
| `JSON`

| Home Battery Power Json Pattern
| `$.battery`

| Home Battery Power Correction Factor
| `-1`

| Home Battery Goal charging power 
|

|===


=== Inverter

[cols="1,3"]
|===

| Source
| `REST`

| Inverter Power Url
| `http://pwplugin:8081/aggregates`

| Result type
| `JSON`

| Inverter Power Json Pattern
| `$.solar`

| Inverter Power Correction Factor
| `1`

|===